version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
      image: postgres:10.4
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=mydb